// @ts-check
// Sidebar is autogenerated from the docs/ folder structure.
// Order is controlled by `sidebar_position` in each markdown frontmatter
// and by `_category_.json` files inside subdirectories.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
